from .erd_cycle import ErdLaundryCycle
from .laundry_const import *

LAUNDRY_CYCLE_MAP = {
    ErdLaundryCycle.CYCLE_0: LAUNDRY_CYCLE_NOTDEFINED,
    ErdLaundryCycle.CYCLE_1: LAUNDRY_CYCLE_NOTDEFINED,
    ErdLaundryCycle.CYCLE_2: LAUNDRY_CYCLE_NOTDEFINED,
    ErdLaundryCycle.CYCLE_3: LAUNDRY_CYCLE_NOTDEFINED,
    ErdLaundryCycle.CYCLE_4: LAUNDRY_CYCLE_NOTDEFINED,
    ErdLaundryCycle.CYCLE_5: LAUNDRY_CYCLE_NOTDEFINED,
    ErdLaundryCycle.CYCLE_6: LAUNDRY_CYCLE_NOTDEFINED,
    ErdLaundryCycle.CYCLE_7: LAUNDRY_CYCLE_NOTDEFINED,
    ErdLaundryCycle.CYCLE_8: LAUNDRY_CYCLE_NOTDEFINED,
    ErdLaundryCycle.CYCLE_9: LAUNDRY_CYCLE_NOTDEFINED,
    ErdLaundryCycle.CYCLE_10: LAUNDRY_CYCLE_NOTDEFINED,
    ErdLaundryCycle.CYCLE_11: LAUNDRY_CYCLE_NOTDEFINED,
    ErdLaundryCycle.CYCLE_12: LAUNDRY_CYCLE_NOTDEFINED,
    ErdLaundryCycle.CYCLE_13: LAUNDRY_CYCLE_NOTDEFINED,
    ErdLaundryCycle.CYCLE_14: LAUNDRY_CYCLE_NOTDEFINED,
    ErdLaundryCycle.CYCLE_15: LAUNDRY_CYCLE_NOTDEFINED,
    ErdLaundryCycle.CYCLE_16: LAUNDRY_CYCLE_NOTDEFINED,
    ErdLaundryCycle.CYCLE_17: LAUNDRY_CYCLE_NOTDEFINED,
    ErdLaundryCycle.CYCLE_18: LAUNDRY_CYCLE_NOTDEFINED,
    ErdLaundryCycle.CYCLE_19: LAUNDRY_CYCLE_NOTDEFINED,
    ErdLaundryCycle.CYCLE_23: LAUNDRY_CYCLE_NOTDEFINED,
    ErdLaundryCycle.CYCLE_29: LAUNDRY_CYCLE_QUICKWASH
}
