import enum

#@enum.unique
class LaundryCycle(enum.Enum):
    CYCLE_ULTRAFRESH_VENT = "UltraFresh Vent"
    CYCLE_NORMAL = "Normal"
    CYCLE_DASH = "---"
    CYCLE_BASKET_CLEAN = "Basket Clean"
    CYCLE_DRAIN_AND_SPIN = "Drain & Spin"
    CYCLE_QUICK_RINSE = "Quick Rinse"
    CYCLE_BULKY_ITEMS = "Bulky Items"
    CYCLE_SANITIZE = "Sanitize"
    CYCLE_TOWELS = "Towels"
    CYCLE_STEAM_REFRESH = "Steam Refresh"
    CYCLE_WHITES = "Whites"
    CYCLE_DARK_COLORS = "Dark Colors"
    CYCLE_JEANS = "Jeans"
    CYCLE_HAND_WASH = "Hand Wash"
    CYCLE_DELICATES = "Delicates"
    CYCLE_SPEED_WASH = "Speed Wash"
    CYCLE_HEAVY_DUTY = "Heavy Duty"
    CYCLE_ALLERGEN = "Allergen"
    CYCLE_POWER_CLEAN = "Power Clean"
    CYCLE_RINSE_AND_SPIN = "Rinse & Spin"
    CYCLE_SINGLE_ITEM_WASH = "Single Item Wash"
    CYCLE_COLORS = "Colors"
    CYCLE_COLD_WASH = "Cold Wash"
    CYCLE_WATER_ON_DEMAND = "Water on Demand"
    CYCLE_TUB_CLEAN = "Tub Clean"
    CYCLE_CASUALS_WITH_STEAM = "Casuals With Steam"
    CYCLE_STAIN_WASH_WITH_STEAM = "Stain Wash With Steam"
    CYCLE_BULKY_BEDDING = "Bulky Bedding"
    CYCLE_QUICK_WASH = "Quick Wash"
    CYCLE_SANITIZE_WITH_OXI = "Sanitize With Oxi"
    CYCLE_SELF_CLEAN = "Self Clean"
    CYCLE_TOWEL = "Towels"
    CYCLE_COTTONS = "Cottons"
    CYCLE_EASY_CARE = "Easy Care"
    CYCLE_ACTIVE_WEAR = "Active Wear"
    CYCLE_TIMED_DRY = "Timed Dry"
    CYCLE_DEWRINKLE = "De-Wrinkle"
    CYCLE_AIR_FLUFF = "Air Fluff"
    CYCLE_STEAM_DEWRINKLE = "Steam Dewrinkle"
    CYCLE_SPEED_DRY = "Speed Dry"
    CYCLE_MIXED = "Mixed"
    CYCLE_QUICK_DRY = "Quick dry"
    CYCLE_CASUALS = "Casuals"
    CYCLE_WARM_UP = "Warm Up"
    CYCLE_ENERGY_SAVER = "Energy Saver"
    CYCLE_ANTIBACTERIAL = "Antibacterial"
    CYCLE_RACK_DRY = "Rack Dry"
    CYCLE_BABY_CARE = "Baby Care"
    CYCLE_AUTO_DRY = "Auto Dry"
    CYCLE_AUTO_EXTRA_DRY = "Auto Extra Dry"
    CYCLE_PERM_PRESS = "Perm Press"
    CYCLE_WASHER_LINK = "Washer Link"
    CYCLE_AUTO_DAMP_DRY = "Auto Damp Dry"

    def stringify(self, **kwargs):
        return self.name.replace("CYCLE_","").replace("_"," ").title()
