from .laundry_enums import ErdLaundryCycle
from .laundry_cycle import LaundryCycle

LAUNDRY_CYCLE_MAP = {
    ErdLaundryCycle.INVALID: LaundryCycle.CYCLE_DASH,
    ErdLaundryCycle.BASKET_CLEAN: LaundryCycle.CYCLE_BASKET_CLEAN,
    ErdLaundryCycle.DRAIN_AND_SPIN: LaundryCycle.CYCLE_DRAIN_AND_SPIN,
    ErdLaundryCycle.QUICK_RINSE: LaundryCycle.CYCLE_QUICK_RINSE,
    ErdLaundryCycle.BULKY_ITEMS: LaundryCycle.CYCLE_BULKY_ITEMS,
    ErdLaundryCycle.SANITIZE: LaundryCycle.CYCLE_SANITIZE,
    ErdLaundryCycle.TOWELS: LaundryCycle.CYCLE_TOWELS,
    ErdLaundryCycle.STEAM_REFRESH: LaundryCycle.CYCLE_STEAM_REFRESH,
    ErdLaundryCycle.NORMAL: LaundryCycle.CYCLE_NORMAL,
    ErdLaundryCycle.WHITES: LaundryCycle.CYCLE_WHITES,
    ErdLaundryCycle.DARK_COLORS: LaundryCycle.CYCLE_DARK_COLORS,
    ErdLaundryCycle.JEANS: LaundryCycle.CYCLE_JEANS,
    ErdLaundryCycle.HAND_WASH: LaundryCycle.CYCLE_HAND_WASH,
    ErdLaundryCycle.DELICATES: LaundryCycle.CYCLE_DELICATES,
    ErdLaundryCycle.SPEED_WASH: LaundryCycle.CYCLE_SPEED_WASH,
    ErdLaundryCycle.HEAVY_DUTY: LaundryCycle.CYCLE_HEAVY_DUTY,
    ErdLaundryCycle.ALLERGEN: LaundryCycle.CYCLE_ALLERGEN,
    ErdLaundryCycle.POWER_CLEAN: LaundryCycle.CYCLE_POWER_CLEAN,
    ErdLaundryCycle.RINSE_AND_SPIN: LaundryCycle.CYCLE_RINSE_AND_SPIN,
    ErdLaundryCycle.SINGLE_ITEM_WASH: LaundryCycle.CYCLE_SINGLE_ITEM_WASH,
    ErdLaundryCycle.COLORS: LaundryCycle.CYCLE_COLORS,
    ErdLaundryCycle.COLD_WASH: LaundryCycle.CYCLE_COLD_WASH,
    ErdLaundryCycle.WATER_ON_DEMAND: LaundryCycle.CYCLE_WATER_ON_DEMAND,
    ErdLaundryCycle.TUB_CLEAN: LaundryCycle.CYCLE_TUB_CLEAN,
    ErdLaundryCycle.CASUALS_WITH_STEAM: LaundryCycle.CYCLE_CASUALS_WITH_STEAM,
    ErdLaundryCycle.STAIN_WASH_WITH_STEAM: LaundryCycle.CYCLE_STAIN_WASH_WITH_STEAM,
    ErdLaundryCycle.BULKY_BEDDING: LaundryCycle.CYCLE_BULKY_BEDDING,
    ErdLaundryCycle.NORMAL2: LaundryCycle.CYCLE_NORMAL,
    ErdLaundryCycle.QUICK_WASH: LaundryCycle.CYCLE_QUICK_WASH,
    ErdLaundryCycle.SANITIZE_WITH_OXI: LaundryCycle.CYCLE_SANITIZE_WITH_OXI,
    ErdLaundryCycle.SELF_CLEAN: LaundryCycle.CYCLE_SELF_CLEAN,
    ErdLaundryCycle.TOWEL: LaundryCycle.CYCLE_TOWELS,
    ErdLaundryCycle.ULTRAFRESH_VENT: LaundryCycle.CYCLE_ULTRAFRESH_VENT,
    ErdLaundryCycle.COTTONS: LaundryCycle.CYCLE_COTTONS,
    ErdLaundryCycle.EASY_CARE: LaundryCycle.CYCLE_EASY_CARE,
    ErdLaundryCycle.ACTIVE_WEAR: LaundryCycle.CYCLE_ACTIVE_WEAR,
    ErdLaundryCycle.TIMED_DRY: LaundryCycle.CYCLE_TIMED_DRY,
    ErdLaundryCycle.DEWRINKLE: LaundryCycle.CYCLE_DEWRINKLE,
    ErdLaundryCycle.AIR_FLUFF: LaundryCycle.CYCLE_AIR_FLUFF,
    ErdLaundryCycle.STEAM_REFRESH2: LaundryCycle.CYCLE_STEAM_REFRESH,
    ErdLaundryCycle.STEAM_DEWRINKLE: LaundryCycle.CYCLE_STEAM_DEWRINKLE,
    ErdLaundryCycle.SPEED_DRY: LaundryCycle.CYCLE_SPEED_DRY,
    ErdLaundryCycle.MIXED: LaundryCycle.CYCLE_MIXED,
    ErdLaundryCycle.QUICK_DRY: LaundryCycle.CYCLE_QUICK_DRY,
    ErdLaundryCycle.CASUALS: LaundryCycle.CYCLE_CASUALS,
    ErdLaundryCycle.WARM_UP: LaundryCycle.CYCLE_WARM_UP,
    ErdLaundryCycle.ENERGY_SAVER: LaundryCycle.CYCLE_ENERGY_SAVER,
    ErdLaundryCycle.ANTIBACTERIAL: LaundryCycle.CYCLE_ANTIBACTERIAL,
    ErdLaundryCycle.RACK_DRY: LaundryCycle.CYCLE_RACK_DRY,
    ErdLaundryCycle.BABY_CARE: LaundryCycle.CYCLE_BABY_CARE,
    ErdLaundryCycle.AUTO_DRY: LaundryCycle.CYCLE_AUTO_DRY,
    ErdLaundryCycle.AUTO_EXTRA_DRY: LaundryCycle.CYCLE_AUTO_EXTRA_DRY,
    ErdLaundryCycle.PERM_PRESS: LaundryCycle.CYCLE_PERM_PRESS,
    ErdLaundryCycle.WASHER_LINK: LaundryCycle.CYCLE_WASHER_LINK,
    ErdLaundryCycle.AUTO_DAMP_DRY: LaundryCycle.CYCLE_AUTO_DAMP_DRY

}
